- name: create loki system group
  group:
    name: "{{ loki_system_group }}"
    system: true
    state: present

- name: create loki system user
  user:
    name: "{{ loki_system_user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ loki_system_group }}"
    createhome: false

- name: "Download loki files"
  become: false
  get_url:
    url: "https://github.com/grafana/loki/releases/download/v{{ loki_version }}/loki-linux-amd64.zip"
    dest: "/tmp/"
  delegate_to: localhost

- name: "Create temporary directory"
  become: false
  file:
    path: /tmp/loki-{{loki_version}}-linux-amd64
    state: directory
  delegate_to: localhost

- name: "Unarchive loki files"
  become: false
  unarchive:
    src: "/tmp/loki-linux-amd64.zip"
    remote_src: yes
    dest: /tmp/loki-{{loki_version}}-linux-amd64
    creates: "/tmp/loki-{{loki_version}}-linux-amd64/loki-linux-amd64"
  delegate_to: localhost
  check_mode: false

- name: propagate loki binary
  copy:
    src: "/tmp/loki-{{loki_version}}-linux-amd64/loki-linux-amd64"
    dest: "/usr/local/bin/loki"
    mode: 0755
    owner: "{{ loki_system_user }}"
    group: "{{ loki_system_group }}"
  notify:
    - restart loki

- name: pre-create loki folders
  file:
    name: "{{ loki_directories }}"
    state: directory
    owner: "{{ loki_system_user }}"
    group: "{{ loki_system_group }}"
  when: loki_directories|length>0

- name: configure loki
  template:
    src: loki.yml.j2
    dest: /etc/loki.yml
    owner: root
    group: root
    mode: 0644
  notify:
    - restart loki

- name: create systemd service unit
  template:
    src: loki.service.j2
    dest: /etc/systemd/system/loki.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart loki
