# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: YAML Lint
      # You may pin to the exact commit or the version
      # uses: ibiqlik/action-yamllint@b2aeacc1b7eeb8c23e84bba320d04fb5d6a323ee
      uses: ibiqlik/action-yamllint@v3.0.0
      with:
        # File(s) or Directory, separate by space if multiple files or folder are specified
        file_or_dir: # optional
        # Path to custom configuration
        config_file: # optional
        # Custom configuration (as YAML source)
        config_data: # optional
        # Format for parsing output [parsable,standard,colored,github,auto]
        format: # optional, default is github
        # Return non-zero exit code on warnings as well as errors
        strict: # optional, default is false
